---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:typescript-sort-keys/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: .
plugins:
  - "@typescript-eslint"
  - sort-destructure-keys
  - typescript-sort-keys
root: true
rules:
  no-console: off
  strict:
    - error
    - global
  curly: warn
  "@typescript-eslint/no-explicit-any": "off"
  import/order:
    - error
    - groups:
        ["builtin", "external", "internal", ["sibling", "parent"], "index"]
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  "@typescript-eslint/no-unused-vars": off # handled by typescript
  sort-destructure-keys/sort-destructure-keys:
    - error
    - caseSensitive: false
settings:
  import/resolver:
    typescript:
    webpack:
      config: ./webpack.config.js
