---
extends:
  - eslint:recommended
  - plugin:@typescript-eslint/recommended
  - plugin:import/errors
  - plugin:typescript-sort-keys/recommended
  - plugin:react-hooks/recommended
parser: "@typescript-eslint/parser"
parserOptions:
  project: ./tsconfig.json
  tsconfigRootDir: .
plugins:
  - "@typescript-eslint"
  - sort-destructure-keys
  - typescript-sort-keys
root: true
rules:
  no-console: off
  strict:
    - error
    - global
  curly: warn
  "@typescript-eslint/no-explicit-any": off
  "@typescript-eslint/no-unused-vars":
    - error
    - argsIgnorePattern: "^_"
      varsIgnorePattern: "^_"
  import/order:
    - error
    - groups:
        - builtin
        - external
        - internal
        - sibling
        - parent
        - index
      alphabetize:
        order: asc
        caseInsensitive: true
      newlines-between: always
  sort-imports:
    - error
    - ignoreDeclarationSort: true
  sort-destructure-keys/sort-destructure-keys:
    - error
    - caseSensitive: false
  react-hooks/exhaustive-deps: error
  sort-keys:
    - error
    - asc
    - caseSensitive: true
      natural: true
settings:
  import/resolver:
    typescript:
    webpack:
      config: ./webpack.config.js
